apiVersion: v1
kind: Service
metadata:
  name: prescription-analyzer-service
  namespace: prescription-system
spec:
  selector:
    app: prescription-analyzer
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer